//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: GateMessage.proto
namespace com.gateserver.clientmessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRequest")]
  public partial class LoginRequest : global::ProtoBuf.IExtensible
  {
    public LoginRequest() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _passwordcode;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"passwordcode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string passwordcode
    {
      get { return _passwordcode; }
      set { _passwordcode = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool passwordcodeSpecified
    {
      get { return this._passwordcode != null; }
      set { if (value == (this._passwordcode== null)) this._passwordcode = value ? this.passwordcode : (string)null; }
    }
    private bool ShouldSerializepasswordcode() { return passwordcodeSpecified; }
    private void Resetpasswordcode() { passwordcodeSpecified = false; }
    
    private string _platform;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"platform", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string platform
    {
      get { return _platform; }
      set { _platform = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool platformSpecified
    {
      get { return this._platform != null; }
      set { if (value == (this._platform== null)) this._platform = value ? this.platform : (string)null; }
    }
    private bool ShouldSerializeplatform() { return platformSpecified; }
    private void Resetplatform() { platformSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginResponse")]
  public partial class LoginResponse : global::ProtoBuf.IExtensible
  {
    public LoginResponse() {}
    
    private int _loginresult;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"loginresult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int loginresult
    {
      get { return _loginresult; }
      set { _loginresult = value; }
    }
    private int? _userType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int? userType
    {
      get { return _userType; }
      set { _userType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool userTypeSpecified
    {
      get { return this._userType != null; }
      set { if (value == (this._userType== null)) this._userType = value ? this.userType : (int?)null; }
    }
    private bool ShouldSerializeuserType() { return userTypeSpecified; }
    private void ResetuserType() { userTypeSpecified = false; }
    
    private string _coordpos;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"coordpos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string coordpos
    {
      get { return _coordpos; }
      set { _coordpos = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool coordposSpecified
    {
      get { return this._coordpos != null; }
      set { if (value == (this._coordpos== null)) this._coordpos = value ? this.coordpos : (string)null; }
    }
    private bool ShouldSerializecoordpos() { return coordposSpecified; }
    private void Resetcoordpos() { coordposSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QueuePosChanged")]
  public partial class QueuePosChanged : global::ProtoBuf.IExtensible
  {
    public QueuePosChanged() {}
    
    private int _queue_pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"queue_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int queue_pos
    {
      get { return _queue_pos; }
      set { _queue_pos = value; }
    }
    private int _maxaccpos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"maxaccpos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxaccpos
    {
      get { return _maxaccpos; }
      set { _maxaccpos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyEnterGame")]
  public partial class NotifyEnterGame : global::ProtoBuf.IExtensible
  {
    public NotifyEnterGame() {}
    
    private int _passcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"passcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int passcode
    {
      get { return _passcode; }
      set { _passcode = value; }
    }
    private string _accountname;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"accountname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string accountname
    {
      get { return _accountname; }
      set { _accountname = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool accountnameSpecified
    {
      get { return this._accountname != null; }
      set { if (value == (this._accountname== null)) this._accountname = value ? this.accountname : (string)null; }
    }
    private bool ShouldSerializeaccountname() { return accountnameSpecified; }
    private void Resetaccountname() { accountnameSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyMessage")]
  public partial class NotifyMessage : global::ProtoBuf.IExtensible
  {
    public NotifyMessage() {}
    
    private byte[] _dataBuf;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dataBuf", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] dataBuf
    {
      get { return _dataBuf; }
      set { _dataBuf = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CloseNotifyMessage")]
  public partial class CloseNotifyMessage : global::ProtoBuf.IExtensible
  {
    public CloseNotifyMessage() {}
    
    private string _reason;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private int _param0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"param0", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int param0
    {
      get { return _param0; }
      set { _param0 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PingRequest")]
  public partial class PingRequest : global::ProtoBuf.IExtensible
  {
    public PingRequest() {}
    
    private int _timePing;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timePing", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timePing
    {
      get { return _timePing; }
      set { _timePing = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientToServerMessage")]
  public partial class ClientToServerMessage : global::ProtoBuf.IExtensible
  {
    public ClientToServerMessage() {}
    
    private com.gateserver.clientmessage.LoginRequest _loginRequest = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"loginRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.gateserver.clientmessage.LoginRequest loginRequest
    {
      get { return _loginRequest; }
      set { _loginRequest = value; }
    }
    private com.gateserver.clientmessage.PingRequest _pingRequest = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pingRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.gateserver.clientmessage.PingRequest pingRequest
    {
      get { return _pingRequest; }
      set { _pingRequest = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerToClientMessage")]
  public partial class ServerToClientMessage : global::ProtoBuf.IExtensible
  {
    public ServerToClientMessage() {}
    
    private com.gateserver.clientmessage.LoginResponse _loginResponse = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"loginResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.gateserver.clientmessage.LoginResponse loginResponse
    {
      get { return _loginResponse; }
      set { _loginResponse = value; }
    }
    private com.gateserver.clientmessage.QueuePosChanged _queuePosChangedNotify = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"queuePosChangedNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.gateserver.clientmessage.QueuePosChanged queuePosChangedNotify
    {
      get { return _queuePosChangedNotify; }
      set { _queuePosChangedNotify = value; }
    }
    private com.gateserver.clientmessage.NotifyMessage _notifyMessage = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"notifyMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.gateserver.clientmessage.NotifyMessage notifyMessage
    {
      get { return _notifyMessage; }
      set { _notifyMessage = value; }
    }
    private com.gateserver.clientmessage.CloseNotifyMessage _closeMessage = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"closeMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.gateserver.clientmessage.CloseNotifyMessage closeMessage
    {
      get { return _closeMessage; }
      set { _closeMessage = value; }
    }
    private com.gateserver.clientmessage.NotifyEnterGame _enterGameMessage = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"enterGameMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.gateserver.clientmessage.NotifyEnterGame enterGameMessage
    {
      get { return _enterGameMessage; }
      set { _enterGameMessage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}