//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace ClientNetwork
{
	public class ConnectionPipeline
	{
		public ConnectionPipeline(Connection connection)
		{
			header = new ConnectionHeaderContext(connection);
			tail = new ConnectionTailContext();
			header.setNextHandler(tail);
		}
		ConnectionHandlerContext header;
		ConnectionHandlerContext tail;
		public void addFirst(string name, ConnectionHandler handler)
		{
			ConnectionHandlerContext ctx = new ConnectionHandlerContext(name, handler);
			header.setNextHandler(ctx);

		}
		public void addLast(string name, ConnectionHandler handler)
		{
			ConnectionHandlerContext ctx = new ConnectionHandlerContext(name, handler);
			tail.setPreHandler(ctx);

		}
		public void write(Object msg)
		{
			tail.fireWrite(msg);
		}
		public void fireRead(Object msg)
		{
			header.fireRead(msg);
		}
		public void readComplete()
		{
			header.readComplete();
		}
        public void fireActive()
        {
            ConnectionHandlerContext ctx = header;
            while (ctx != null)
            {
                ctx.Active();
                ctx = ctx.getNextHandler();
            }
        }
        public void fireDeactive()
        {
            ConnectionHandlerContext ctx = tail;
            while (ctx != null)
            {
                ctx.Deactive();
                ctx = ctx.getPreHandler();
            }

        }
	}
}

