//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Text;


namespace ClientNetwork
{
	public class ConnectionTailContext : ConnectionHandlerContext
	{
		const String TAILER_NAME = "tailcontext";
		public ConnectionTailContext():base(TAILER_NAME,null,true,false)
		{
		}
		public override void invokeWrite(object message)
		{
			throw new NotImplementedException();
		}

		public override void invokeRead(object message)
		{
			//base.invokeRead (message);
			ByteBuf buf = (ByteBuf)message;
			Encoding encoding = System.Text.UTF8Encoding.Default;
			System.Console.WriteLine("Not Implemented buffer " + encoding.GetString(buf.getBuffer(), buf.getReaderIndex(), buf.getWriterIndex()));
		}

		public override void invokeReadComplete()
		{
			System.Console.WriteLine("Not Implemented buffer Completed end");
			//base.invokeReadComplete ();
		}
	}
}

