//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace ClientNetwork
{
	public class DebugInboundHandler : InboundHandlerAdapter
	{
		public DebugInboundHandler()
		{
		}
		
		public override void read(ConnectionHandlerContext ctx, object msg)
		{
			ByteBuf inputBuf = (ByteBuf)msg;
			System.Console.WriteLine(inputBuf.ToString());
			
			
		}
	    public override void deactive(ConnectionHandlerContext ctx)
        {
            System.Console.WriteLine("Connection is Closed!");
        }
	}
}

