//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;



	public class MessageActionTable
	{
        class TriggerInfo
        {
            
            public Action<object> trigger;
            public bool triggerOnce;

        };
        public MessageActionTable()
		{

		}
		public void RegisterMessageTrigger<T>(Action<T> action,bool once)
		{
            TriggerInfo info = new TriggerInfo();
            info.triggerOnce = once;
            info.trigger = (object obj) =>
			{
				T message = (T)obj;
				action(message);

			};
            lock(this)
            {
                table[typeof(T)] =  info;
            }
            
		}
        public void RegisterMessageTrigger<T>(Action<T> action)
        {
            RegisterMessageTrigger(action,false);
        }
		public void fireMessageTrigger<T>(T message)
		{
			System.Type type = typeof(T);

            TriggerInfo info;
            lock(this)
            {
                table.TryGetValue(type, out  info);
                if (info != null)
                {
                    if (info.triggerOnce)
                    {
                        table.Remove(type);
                    }
                }
            }
			
			if (info != null) {
                if (info.trigger != null)
				    info.trigger(message);
			}

		}
        IDictionary<System.Type, TriggerInfo> table = new Dictionary<System.Type, TriggerInfo>();

	    public void Clear()
	    {
	        table.Clear();
	    }
	}


