//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO;


namespace ClientNetwork
{
	public class ProtobufEncoder <T> : OutboundHandlerAdapter
	{
		const int MaxPacketSize = 2048 * 2048 * 4;
		public ProtobufEncoder()
		{
			memStream = new MemoryStream(tempBuf.getBuffer());
		
		}

		MemoryStream memStream;
		ByteBuf tempBuf = ByteBuf.allocOne(MaxPacketSize);
		
        
		public override void  write(ConnectionHandlerContext ctx, object msg)
		{
			tempBuf.MakeBufferEmpty();
		    memStream.Position = 0;
			ProtoBuf.Serializer.Serialize(memStream, msg);
			int writeIndex = (int)memStream.Position;
			tempBuf.setWriteIndex(writeIndex);

			ctx.fireWrite(tempBuf);
		}

		

        
    }
}

