//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO;


namespace ClientNetwork
{
	public class ProtobufDecoder<T> : InboundHandlerAdapter
	{

		Action<T> receiveObjFunc;
		public ProtobufDecoder(Action<T> recvFunc)
		{
			receiveObjFunc = recvFunc;
		}
		public override void active(ConnectionHandlerContext ctx)
		{
		
		}

		public override void deactive(ConnectionHandlerContext ctx)
		{
		
		}

		public override void read(ConnectionHandlerContext ctx, object msg)
		{
			ByteBuf buf = (ByteBuf)msg;
			//System.Console.WriteLine("receive bytes " + buf.remainBytes());
			MemoryStream ms = new MemoryStream(buf.getBuffer(), buf.getReaderIndex(), buf.remainBytes());
			T obj = ProtoBuf.Serializer.Deserialize<T>(ms);
            buf.skipReaderIndex((int)ms.Position);
			if (receiveObjFunc != null)
				receiveObjFunc(obj);


		}

		
	}
}

