//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: adconfig.proto
namespace autodemo
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Paths")]
  public partial class Paths : global::ProtoBuf.IExtensible
  {
    public Paths() {}
    
    private string _caffe = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"caffe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string caffe
    {
      get { return _caffe; }
      set { _caffe = value; }
    }
    private string _proj_path = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"proj_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string proj_path
    {
      get { return _proj_path; }
      set { _proj_path = value; }
    }
    private string _data_root = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"data_root", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data_root
    {
      get { return _data_root; }
      set { _data_root = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ImageMsg")]
  public partial class ImageMsg : global::ProtoBuf.IExtensible
  {
    public ImageMsg() {}
    
    private int _width = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int width
    {
      get { return _width; }
      set { _width = value; }
    }
    private int _height = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int height
    {
      get { return _height; }
      set { _height = value; }
    }
    private int _channels = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"channels", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int channels
    {
      get { return _channels; }
      set { _channels = value; }
    }
    private byte[] _image_data = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"image_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] image_data
    {
      get { return _image_data; }
      set { _image_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}